export function handleFailure(err: Error) {
  alert(err.message);
}
